name: test-s3-cf-upload
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
jobs:
  s3-cf-upload:
    name: "Test: s3-cf-upload"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello World
        uses: ./
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          s3_bucket: ${{ env.BUCKET }}
          domain: dev-4.taradito.com
          publish_dir: "fe/apps/web/dist"
          destination_dir: ${{ env.DESTINATION_DIRECTORY }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run package --if-present
