name: test-s3-cf-upload
on:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly

    permissions:
      contents: write
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all

      - name: Publish artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mv gitignore-build .gitignore
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add .
          git commit -m "Add build artifacts" > /dev/null
          git push origin HEAD:v0.0.3 -f
