name: test-s3-cf-upload
on:
  push:
    branches:
      - main
      
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all
          
      - name: Publish artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          mv gitignore-build .gitignore
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add .
          git commit -m "Add build artifacts" > /dev/null
          git push origin HEAD:v0.0.1 -f
          
      - name: Upload and Distribute
        uses: ./ # Replace with the correct action for S3 upload
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3_bucket: ${{ secrets.BUCKET }} # Ensure BUCKET is defined as a secret
          domain: dev-4.taradito.com
          publish_dir: "fe/apps/web/dist"
          destination_dir: ${{ secrets.DESTINATION_DIRECTORY }} # Ensure DESTINATION_DIRECTORY is defined as a secret
